### ISSUE TITLE
Overwrite Octodash commands

### ISSUE THREAD

**Issue by rongith** [synman/OctoPrint-SystemCommandEditor#2]
**Describe the bug**
If I add a command through SystemCommandEditor plugin, it will overwrite Octodash commands.

**To Reproduce**
Install Octodash
Install SystemCommandEditor plugin
Add a command with SystemCommandEditor  
It will add the folowing lines in config.yaml
```
system:
  actions:
  - action: Restart camera-streamer
    command: sudo systemctl restart camera-streamer-raspi-v3-12MP
    name: Restart camera-streamer
```
If I remove the lines added by SystemCommandEditor plugin in cong.yalm and restart Octoprint, I got back my Octodash commands.

**Expected behavior**
No overwrite of Octodash commands.
I don't know what part to blame for that behavior:

- Octoprint API
- Octodash
- SystemCommandEditor

**Screenshots**
Commands from Octodash:
![image](https://github.com/synman/OctoPrint-SystemCommandEditor/assets/7966342/886ed22c-7a0a-4a52-ad79-9ac475e4f786)
Commands after adding a command through SystemCommandEditor 
![image](https://github.com/synman/OctoPrint-SystemCommandEditor/assets/7966342/0f9cdcb1-23e4-46d8-9260-6ae5ecab2873)

**System**
Octoprint 1.9.3
Octodash 2.3.1
SystemCommandEditor 1.0.0
RaspberryPIOS Bookworm
